--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BOFOII/TheBridge
build-by-default: true
branches:
- main
projects:
  TheBridge:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.1.0
      - src: Ifera/ScoreFactory/ScoreFactory
        version: ^3.1.0
...
